---
title: 生成器和Promise
date: 2021-04-22
tags:
 - ES6简述
categories: 
 - ECMAScript6
---

# 生成器和Promise

## 生成器 generator

ES2015提供的生成器

使用 function * 声明, 使用next()才开始执行, 遇到yield就停止, 下次使用next则继续, 并且next()执行后返回一个值, 包含了yield返回的value和一个done属性, done属性要用于表示生成器是否执行完成

并且next()中可以带参数, 当带参执行next时候, yield可以返回一个值，这个值就是这个参数

如果调用generator.throw()方法，也可以让生成器继续执行，但是会抛出一个异常

生成器中 yield前面有return和普通函数一样，不管后面还有没有yield都不会执行了

> 注意: 第一次调用next是执行yield后面的值, 但是第二次调用next并且传参, 就可以把这个参数作为 yield的返回值使用了
> 也就是说第二次调用next是把参数作为第一个yield的值并且执行后续的逻辑, 执行到第二个yield为止, 这一次的next是返回第二个yield的执行结
> 生成器对象也实现了iterator接口

### 应用

```javaScript
// 发号器

function * createIdMaker() {
    let id = 1;
    while(true) {
        yield id++;
    }
}

const idMaker = createIdMaker();// 这样就实现了一个发号器, 每一次使用next()就会得到一个自增后的id

// 使用生成器重构上面的迭代器
const todos = {
    life: ['吃饭', '睡觉', '打游戏'],
    learn: ['js', '数据结构', '计算机网络'],
    work: ['敲代码'],
    // * 提供者提供一个遍历接口
    [Symbol.iterator]: function * () {
        const store = [...this.life, ...this.learn, ...this.work];
        for (let item of store) {
            yield item;
        }
    }
}

// 实现一个用于promise的co, 自动调用next直到走完整个生成器, 让yield看起来是一个同步的过程
function co (generator) {
    const g = generator();
    function handleResult(res) {
        if (res.done) return;
        res.value.then(data => {
            handleResult(g.next(data));
        }, err => {
            throw Error(err);
        })
    }
    handleResult(g.next())
}

```

## Promise

新增Promise, 模块一说过



```javaScript
// 手写Promise
const FULFILLED = 'fulfilled';
const PENDING = 'pending';
const REJECTED = 'rejected';

class MyPromise {
    constructor(executor) {
        try{
            executor(this.resolve, this.reject);
        } catch (e) {
            this.reject(e);
        }
    }
    state = PENDING;
    value = undefined;
    reason = undefined;
    successCallbacks = [];
    failedCallbacks = [];

    resolve = (value) => {
        if (this.state === PENDING) {
            this.state = FULFILLED;
            this.value = value;
            while(this.successCallbacks.length) {
                this.successCallbacks.shift()();
            }
        }
    }

    reject = (reason) => {
        if (this.state === PENDING) {
            this.state = REJECTED;
            this.reason = reason;
            while(this.failedCallbacks.length) {
                this.failedCallbacks.shift()();
            }
        }
    }

    then (successCallback, failCallback) {
        successCallback = typeof successCallback === 'function' ? successCallback : v => v;
        failCallback = typeof failCallback === 'function' ? failCallback : err => new Error(err);
        const promise2 = new MyPromise((resolve, reject) => {
            if (this.state === FULFILLED) {
                queueMicrotask(() => {
                    try {
                        const x = successCallback();
                        this.resolvePromise(x, promise2, resolve, reject);
                    } catch (e) {
                        reject(e);
                    }
                })
            } else if (this.state === REJECTED) {
                queueMicrotask(() => {
                    try {
                        const x = failCallback();
                        this.resolvePromise(x, promise2, resolve, reject)
                    } catch (e) {
                        reject(e)
                    }
                })
            } else {
                this.successCallbacks.push(queueMicrotask(() => {
                    try {
                        const x = successCallback();
                        this.resolvePromise(x, promise2, resolve, reject);
                    } catch (e) {
                        reject(e);
                    }
                }));
                this.failedCallbacks.push(queueMicrotask(() => {
                    try {
                        const x = failCallback();
                        this.resolvePromise(x, promise2, resolve, reject)
                    } catch (e) {
                        reject(e)
                    }
                }))
            }

            return promise2;
        })
    }

    // * 辅助函数, 用于判断是否同一个then中返回的Promise和当前Promise是否同一个
    resolvePromise(x, promise2, resolve, reject) {
        if (x === promise2) {
            return reject(new TypeError('Chaining cycle detected for promise #<Promise>'))
        }
        if (x instanceof MyPromise) {
            x.then(resolve, reject);
        } else {
            resolve(x)
        }
    }

    static all(promiseArr) {
        let res = [];
        let index = 0;
        function addData(key, value, resolve) {
            res[key] = value;
            index++;
            if (index === promiseArr.length) {
                resolve(res);
            }
        }

        return new MyPromise((resolve, reject) => {
            for (let i = 0; i < promiseArr.length; i++) {
                if (promiseArr[i] instanceof MyPromise) {
                    promiseArr[i].then(res => {
                        addData(i, res, resolve);
                    }, err => {
                        reject(err);
                    })
                } else {
                    addData(i, promiseArr[i], resolve);
                }       
            }
        })
    }

    static resolve(value) {
        if (value instanceof MyPromise) return;
        return new MyPromise(resolve => { resolve(value) });
    }

    static reject(reason) {
        if (value instanceof MyPromise) return;
        return new MyPromise(undefined, reject => { reject(value) });
    }

    static race(promiseArr) {
        let res = [];
        return new Promise((resolve, reject) => {
            for (let index of promiseArr) {
                let current = promiseArr[index];
                if (current instanceof MyPromise) {
                    current.then(res => {
                        resolve(res);
                    }, err => {
                        reject(err);
                    })
                } else {
                    resolve(current);
                }
            }
        })
    }

    static allSettled(promiseArr) {
        let res = [];
        let index = 0;
        function addData (key. value, resolve, status) {
            if (status === FULFILLED) {
                res[key] = {};
                res[key].value = value;
                res[key].status = FULFILLED;
            } else if (status === REJECTED) {
                res[key] = {};
                res[key].reason = value;
                res[key].status = REJECTED;
            }
            index++;
            if (index === promiseArr.length) {
                resolve(res);
            }
        }
        return new Promise((resolve, reject) => {
            for (let i of promiseArr) {
                let current = promiseArr[i];
                if (current instanceof MyPromise) {
                    current.then((val) => {
                        addData(i, val, resolve, FULFILLED);
                    }, err => {
                        addData(i, err, resolve, REJECTED);
                    });
                } else {
                    addData(i, current, resolve, FULFILLED);
                }
            }
        })
    }

    finally(callback) {
        return this.then(val => {
            return MyPromise.resolve(callback()).then(() => val);
        }, err => {
            return MyPromise.resolve(callback()).then(() => {throw err});
        })
    }

    catch(callback) {
        return this.then(undefined, callback);
    }
}
```
